lang: en

timezone: Africa/Nairobi

title: "Bildard Blair"

tagline: "Computer Science Graduate | Cybersecurity & Network Enthusiast | Full-Stack Developer"

description: "Professional portfolio showcasing my experience in cybersecurity, networking, software development, technical support, and project-based learning."

url: "https://Blair606.github.io"

github:
  username: Blair606

twitter:
  username: BobbyZiggler

social:
  name: Bildard Blair Odhiambo
  email: bobbyziggler606@gmail.com

  links:
    - https://github.com/Blair606
    - https://www.linkedin.com/in/bildard-blair-302a4228b
    - https://x.com/BobbyZiggler

theme_mode:

avatar: /assets/img/profile.jpg

social_preview_image: /assets/img/portfolio-preview.png

toc: true

paginate: 10

baseurl: ""

collections:
  tabs:
    output: true
    sort_by: order

jekyll-archives:
  enabled:
    - categories
    - tags

  layouts:
    category: category
    tag: tag

  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
